server:
  port: 10028
  forward-headers-strategy: framework
  servlet:
    context-path: /mtc-live/v1.0
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
file:
  uploadDir: ${user.dir}/storage